import { BusinessConfig } from "@/types/config";

export const generalRetailConfig: BusinessConfig = {
  enabled: false, // Hidden: Phase 3 focuses on medical_distributor only
  id: "general-retail-superstore",
  businessType: "general_retail",
  businessName: "Kerala Super Mart",
  tagline: "Daily Needs, Groceries & Superstore Retail",
  currency: "INR",
  language: "en",
  gstin: "32KSMART5566G1Z9",
  phone: "+91 94000 88776",
  email: "billing@keralasmart.com",
  address: "City Superstore Complex, Commercial Street",
  city: "Kollam",
  state: "Kerala",
  pincode: "691001",
  branding: {
    brandColor: "#0284c7",
    accentColor: "#38bdf8",
    tagline: "Fresh Groceries & Everyday Superstore",
    theme: "light",
  },
  terminology: {
    customer: "Customer",
    customerPlural: "Customers",
    supplier: "FMCG Supplier",
    supplierPlural: "Suppliers",
    product: "Item",
    productPlural: "Items",
    invoice: "Retail Bill",
    invoicePlural: "Retail Bills",
    purchase: "Purchase Invoice",
    purchasePlural: "Purchase Invoices",
    quotation: "Estimate",
    estimate: "Estimate",
    deliveryNote: "Delivery Slip",
    paymentReceipt: "Payment Receipt",
    expense: "Expense",
    inventory: "Superstore Stock",
    creditNote: "Return Credit Memo",
    taxLabel: "GSTIN",
  },
  modules: {
    dashboard: true,
    customers: true,
    suppliers: true,
    products: true,
    inventory: true,
    sales: true,
    purchases: true,
    documents: true,
    payments: true,
    expenses: true,
    reports: true,
    employees: true,
  },
  productFields: [
    { id: "itemName", label: "Item Name", type: "text", required: true, visible: true, placeholder: "e.g. Basmati Rice 5kg", showInTable: true, showInForm: true },
    { id: "category", label: "Category", type: "select", required: true, visible: true, options: ["Groceries", "Beverages", "Personal Care", "Packaged Food", "Household"], showInTable: true, showInForm: true },
    { id: "barcode", label: "Barcode / EAN", type: "text", required: false, visible: true, placeholder: "8901234567890", showInTable: true, showInForm: true },
    { id: "mrp", label: "MRP (₹)", type: "currency", required: true, visible: true, placeholder: "250", showInTable: true, showInForm: true },
    { id: "purchasePrice", label: "Purchase Price (₹)", type: "currency", required: true, visible: true, showInTable: false, showInForm: true },
    { id: "sellingPrice", label: "Retail Price (₹)", type: "currency", required: true, visible: true, showInTable: true, showInForm: true },
    { id: "gstRate", label: "GST Rate (%)", type: "number", required: true, visible: true, placeholder: "5", showInTable: true, showInForm: true },
  ],
  documentTypes: [
    { id: "retail_bill", label: "Retail Bill", shortLabel: "Bill", prefix: "KSM-POS", enabled: true, template: "minimal", numberingEnabled: true },
    { id: "purchase_invoice", label: "Purchase Invoice", shortLabel: "Purchase", prefix: "KSM-PUR", enabled: true, template: "classic", numberingEnabled: true },
    { id: "estimate", label: "Estimate", shortLabel: "Estimate", prefix: "KSM-EST", enabled: true, template: "modern", numberingEnabled: true },
  ],
  dashboardWidgets: [
    { id: "pos_sales", title: "Counter POS Sales", type: "metric", enabled: true, width: "half" },
    { id: "top_categories", title: "Top Selling Categories", type: "chart", enabled: true, width: "half" },
  ],
  paymentConfig: {
    acceptedMethods: ["upi", "cash", "card"],
    defaultMethod: "upi",
    allowCredit: false,
  },
  taxConfig: {
    taxSystem: "gst",
    defaultGstRate: 5,
    gstinRequired: false,
    hsnSacRequired: true,
    taxLabel: "GSTIN",
  },
  numberingConfig: {
    invoicePrefix: "KSM-POS",
    purchasePrefix: "KSM-PUR",
    quotationPrefix: "KSM-EST",
    sequenceStart: 1001,
    resetFrequency: "yearly",
  },
};
