import { BusinessConfig } from "@/types/config";

export const hardwareShopConfig: BusinessConfig = {
  enabled: false, // Hidden: Phase 3 focuses on medical_distributor only
  id: "kerala-hardware-centre",
  businessType: "hardware_shop",
  businessName: "Kerala Hardware Centre",
  tagline: "Building Materials, Tools & Electrical Supplies",
  currency: "INR",
  language: "en",
  gstin: "32XYZPA9876K1Z2",
  phone: "+91 98950 55443",
  email: "sales@keralahardware.in",
  address: "Main Junction, NH Bypass",
  city: "Thrissur",
  state: "Kerala",
  pincode: "680001",
  branding: {
    brandColor: "#d97706",
    accentColor: "#f59e0b",
    tagline: "Building Materials & Hardware Tools",
    theme: "light",
  },
  terminology: {
    customer: "Customer",
    customerPlural: "Customers",
    supplier: "Hardware Distributor",
    supplierPlural: "Distributors",
    product: "Item",
    productPlural: "Items",
    invoice: "Sales Invoice",
    invoicePlural: "Sales Invoices",
    purchase: "Purchase Bill",
    purchasePlural: "Purchase Bills",
    quotation: "Quotation",
    estimate: "Estimate",
    deliveryNote: "Delivery Note",
    paymentReceipt: "Payment Receipt",
    expense: "Expense",
    inventory: "Stock Inventory",
    creditNote: "Credit Note",
    taxLabel: "GSTIN",
  },
  modules: {
    dashboard: true,
    customers: true,
    suppliers: true,
    products: true,
    inventory: true,
    sales: true,
    purchases: true,
    documents: true,
    payments: true,
    expenses: true,
    reports: true,
    employees: true,
  },
  productFields: [
    { id: "brand", label: "Brand", type: "text", required: true, visible: true, placeholder: "e.g. Bosch / Supreme / Taparia", showInTable: true, showInForm: true },
    { id: "category", label: "Category", type: "select", required: true, visible: true, options: ["Plumbing", "Electricals", "Power Tools", "Fasteners", "Sanitaryware"], showInTable: true, showInForm: true },
    { id: "size", label: "Size / Dimension", type: "text", required: false, visible: true, placeholder: "e.g. 1/2 inch / 100mm", showInTable: true, showInForm: true },
    { id: "material", label: "Material Grade", type: "text", required: false, visible: true, placeholder: "e.g. Brass / PVC / Stainless Steel", showInTable: false, showInForm: true },
    { id: "unit", label: "Unit", type: "select", required: true, visible: true, options: ["Pieces", "Meters", "Boxes", "Kg", "Sets"], showInTable: true, showInForm: true },
    { id: "sku", label: "SKU / Code", type: "text", required: true, visible: true, placeholder: "e.g. PLMB-VALVE-05", showInTable: true, showInForm: true },
    { id: "purchasePrice", label: "Purchase Price (₹)", type: "currency", required: true, visible: true, showInTable: false, showInForm: true },
    { id: "sellingPrice", label: "Selling Price (₹)", type: "currency", required: true, visible: true, showInTable: true, showInForm: true },
    { id: "gstRate", label: "GST Rate (%)", type: "number", required: true, visible: true, placeholder: "18", showInTable: true, showInForm: true },
  ],
  documentTypes: [
    { id: "sales_invoice", label: "Sales Invoice", shortLabel: "Invoice", prefix: "KHC-INV", enabled: true, template: "modern", numberingEnabled: true, requiresDelivery: true },
    { id: "quotation", label: "Quotation", shortLabel: "Quote", prefix: "KHC-QT", enabled: true, template: "classic", numberingEnabled: true },
    { id: "purchase_bill", label: "Purchase Bill", shortLabel: "Purchase", prefix: "KHC-PB", enabled: true, template: "classic", numberingEnabled: true },
    { id: "delivery_note", label: "Delivery Note", shortLabel: "Delivery Slip", prefix: "KHC-DN", enabled: true, template: "minimal", numberingEnabled: true, requiresDelivery: true },
  ],
  dashboardWidgets: [
    { id: "sales_trend", title: "Sales Trend", type: "chart", enabled: true, width: "full" },
    { id: "fast_moving", title: "Fast Moving Hardware Items", type: "list", enabled: true, width: "half" },
    { id: "contractor_dues", title: "Contractor Pending Balances", type: "metric", enabled: true, width: "half" },
  ],
  paymentConfig: {
    acceptedMethods: ["cash", "upi", "bank_transfer", "card", "cheque"],
    defaultMethod: "cash",
    allowCredit: true,
    maxCreditDays: 30,
  },
  taxConfig: {
    taxSystem: "gst",
    defaultGstRate: 18,
    gstinRequired: true,
    hsnSacRequired: true,
    taxLabel: "GSTIN",
  },
  numberingConfig: {
    invoicePrefix: "KHC-INV",
    purchasePrefix: "KHC-PB",
    quotationPrefix: "KHC-QT",
    sequenceStart: 1001,
    resetFrequency: "yearly",
  },
};
