import { BusinessConfig } from "@/types/config";

export const medicalDistributorConfig: BusinessConfig = {
  id: "medcare-distributors",
  businessType: "medical_distributor",
  businessName: "Revolga Biogenics",
  tagline: "Complete Pharma Wholesale Management System",
  currency: "INR",
  language: "en",
  gstin: "32ABCDC1234D1Z8",
  phone: "+91 94471 99887",
  email: "orders@revolgabiogenics.com",
  address: "Pharma City Complex, Medical College Road",
  city: "Kozhikode",
  state: "Kerala",
  pincode: "673008",
  branding: {
    brandColor: "#059669",
    accentColor: "#10b981",
    tagline: "Your Trusted Pharma Wholesale Partner",
    theme: "light",
  },
  enabled: true,
  terminology: {
    customer: "Customer",
    customerPlural: "Customers",
    supplier: "Supplier",
    supplierPlural: "Suppliers",
    product: "Medicine",
    productPlural: "Medicines",
    invoice: "Tax Invoice",
    invoicePlural: "Tax Invoices",
    purchase: "Purchase Bill",
    purchasePlural: "Purchase Bills",
    quotation: "Quotation",
    estimate: "Pro-forma Invoice",
    deliveryNote: "Delivery Challan",
    paymentReceipt: "Payment Receipt",
    expense: "Expense",
    inventory: "Medicine Stock",
    creditNote: "Credit Note",
    taxLabel: "GSTIN / Drug License No.",
  },
  modules: {
    dashboard: true,
    customers: true,
    suppliers: true,
    products: true,
    inventory: true,
    sales: true,
    purchases: true,
    documents: true,
    payments: true,
    expenses: true,
    reports: true,
    employees: false,
  },
  productFields: [
    { id: "medicineName", label: "Medicine Name", type: "text", required: true, visible: true, placeholder: "e.g. Dolo 650mg", showInTable: true, showInForm: true },
    { id: "genericName", label: "Generic Name", type: "text", required: true, visible: true, placeholder: "e.g. Paracetamol 650mg", showInTable: true, showInForm: true },
    { id: "brand", label: "Brand", type: "text", required: false, visible: true, placeholder: "e.g. Dolo", showInTable: false, showInForm: true },
    { id: "manufacturer", label: "Manufacturer", type: "text", required: true, visible: true, placeholder: "e.g. Mankind Pharma", showInTable: true, showInForm: true },
    { id: "category", label: "Category", type: "select", required: true, visible: true, options: ["Antibiotics", "Analgesics", "Antidiabetics", "Cardiovascular", "Vitamins & Supplements", "Gastroenterology", "Dermatology", "Neurology", "Respiratory", "Ophthalmology"], showInTable: true, showInForm: true },
    { id: "composition", label: "Composition", type: "text", required: false, visible: true, placeholder: "Active ingredient(s)", showInTable: false, showInForm: true },
    { id: "dosageForm", label: "Dosage Form", type: "select", required: true, visible: true, options: ["Tablet", "Capsule", "Syrup", "Injection", "Cream", "Drops", "Inhaler", "Gel", "Ointment", "Powder"], showInTable: false, showInForm: true },
    { id: "strength", label: "Strength", type: "text", required: true, visible: true, placeholder: "e.g. 500mg", showInTable: false, showInForm: true },
    { id: "packSize", label: "Pack Size", type: "text", required: true, visible: true, placeholder: "e.g. 10 Tablets", showInTable: true, showInForm: true },
    { id: "unit", label: "Unit", type: "select", required: true, visible: true, options: ["Strip", "Bottle", "Vial", "Tube", "Box", "Inhaler", "Packet"], showInTable: false, showInForm: true },
    { id: "sku", label: "SKU / Product Code", type: "text", required: false, visible: true, showInTable: true, showInForm: true },
    { id: "hsnCode", label: "HSN Code", type: "text", required: false, visible: true, placeholder: "e.g. 30049099", showInTable: false, showInForm: true },
    { id: "mrp", label: "MRP (₹)", type: "currency", required: true, visible: true, placeholder: "120", showInTable: true, showInForm: true },
    { id: "purchasePrice", label: "Purchase Price (₹)", type: "currency", required: true, visible: true, showInTable: false, showInForm: true },
    { id: "sellingPrice", label: "Selling Price (₹)", type: "currency", required: true, visible: true, showInTable: true, showInForm: true },
    { id: "discount", label: "Discount (%)", type: "number", required: false, visible: true, showInTable: false, showInForm: true },
    { id: "gstRate", label: "GST Rate (%)", type: "select", required: true, visible: true, options: ["0", "5", "12", "18"], showInTable: true, showInForm: true },
    { id: "currentStock", label: "Current Stock", type: "number", required: false, visible: true, showInTable: true, showInForm: false },
    { id: "minStockLevel", label: "Min Stock Level", type: "number", required: false, visible: true, showInTable: false, showInForm: true },
    { id: "reorderLevel", label: "Reorder Level", type: "number", required: false, visible: true, showInTable: false, showInForm: true },
    { id: "prescriptionRequired", label: "Prescription Required", type: "boolean", required: false, visible: true, showInTable: true, showInForm: true },
    { id: "status", label: "Status", type: "select", required: true, visible: true, options: ["active", "inactive", "discontinued"], showInTable: true, showInForm: true },
  ],
  documentTypes: [
    { id: "sales_invoice", label: "Tax Invoice", shortLabel: "Invoice", prefix: "INV", enabled: true, template: "professional", numberingEnabled: true, supportsBatches: true },
    { id: "purchase_bill", label: "Purchase Bill", shortLabel: "Purchase", prefix: "PUR", enabled: true, template: "classic", numberingEnabled: true, supportsBatches: true },
    { id: "delivery_note", label: "Delivery Challan", shortLabel: "Challan", prefix: "DC", enabled: true, template: "minimal", numberingEnabled: true, requiresDelivery: true },
    { id: "receipt", label: "Payment Receipt", shortLabel: "Receipt", prefix: "REC", enabled: true, template: "minimal", numberingEnabled: true },
    { id: "credit_note", label: "Credit Note", shortLabel: "Credit", prefix: "CN", enabled: true, template: "classic", numberingEnabled: true },
    { id: "debit_note", label: "Debit Note", shortLabel: "Debit", prefix: "DN", enabled: true, template: "classic", numberingEnabled: true },
    { id: "sales_return", label: "Sales Return", shortLabel: "S. Return", prefix: "SR", enabled: true, template: "classic", numberingEnabled: true, supportsBatches: true },
    { id: "purchase_return", label: "Purchase Return", shortLabel: "P. Return", prefix: "PR", enabled: true, template: "classic", numberingEnabled: true, supportsBatches: true },
    { id: "quotation", label: "Quotation", shortLabel: "Quote", prefix: "QT", enabled: true, template: "professional", numberingEnabled: true },
  ],
  dashboardWidgets: [
    { id: "todays_sales", title: "Today's Sales", type: "metric", enabled: true, width: "third" },
    { id: "todays_purchases", title: "Today's Purchases", type: "metric", enabled: true, width: "third" },
    { id: "total_outstanding", title: "Total Outstanding", type: "metric", enabled: true, width: "third" },
    { id: "receivables", title: "Receivables", type: "metric", enabled: true, width: "third" },
    { id: "payables", title: "Payables", type: "metric", enabled: true, width: "third" },
    { id: "stock_value", title: "Total Stock Value", type: "metric", enabled: true, width: "third" },
    { id: "low_stock", title: "Low Stock Medicines", type: "metric", enabled: true, width: "third" },
    { id: "near_expiry", title: "Near Expiry Medicines", type: "metric", enabled: true, width: "third" },
    { id: "expired", title: "Expired Medicines", type: "metric", enabled: true, width: "third" },
    { id: "recent_sales", title: "Recent Sales", type: "list", enabled: true, width: "half" },
    { id: "top_medicines", title: "Top Selling Medicines", type: "list", enabled: true, width: "half" },
    { id: "expiry_alert", title: "Near Expiry Alerts", type: "table", enabled: true, width: "full" },
  ],
  paymentConfig: {
    acceptedMethods: ["cash", "bank_transfer", "upi", "cheque"],
    defaultMethod: "bank_transfer",
    allowCredit: true,
    maxCreditDays: 45,
  },
  taxConfig: {
    taxSystem: "gst",
    defaultGstRate: 12,
    gstinRequired: true,
    hsnSacRequired: true,
    taxLabel: "GSTIN / Drug License No.",
  },
  numberingConfig: {
    invoicePrefix: "INV",
    purchasePrefix: "PUR",
    quotationPrefix: "QT",
    sequenceStart: 1,
    resetFrequency: "yearly",
  },
  expirySettings: {
    nearExpiryDays: [30, 60, 90],
    alertEnabled: true,
  },
  inventorySettings: {
    trackBatches: true,
    allowNegativeStock: false,
    autoDeductOnSale: true,
  },
  website: {
    enabled: true,
    pages: ["home", "about", "medicines", "categories", "manufacturers", "services", "dealer-registration", "request-quote", "contact"],
  },
};
