import { BusinessConfig } from "@/types/config";

export const paintShopConfig: BusinessConfig = {
  enabled: false, // Hidden: Phase 3 focuses on medical_distributor only
  id: "colour-world-paints",
  businessType: "paint_shop",
  businessName: "Colour World Paints",
  tagline: "Quality Paints, Tints & Industrial Coating Solutions",
  currency: "INR",
  language: "en",
  gstin: "32AAAAA0000A1Z5",
  phone: "+91 98470 12345",
  email: "contact@colourworldpaints.in",
  address: "Building No. 12/450, M.G. Road",
  city: "Kochi",
  state: "Kerala",
  pincode: "682011",
  branding: {
    brandColor: "#2563eb",
    accentColor: "#3b82f6",
    tagline: "Quality Paints & Coating Solutions",
    theme: "light",
  },
  terminology: {
    customer: "Customer",
    customerPlural: "Customers",
    supplier: "Paint Manufacturer",
    supplierPlural: "Manufacturers",
    product: "Paint",
    productPlural: "Paints",
    invoice: "Sales Bill",
    invoicePlural: "Sales Bills",
    purchase: "Purchase Bill",
    purchasePlural: "Purchase Bills",
    quotation: "Quotation",
    estimate: "Estimate / Quote",
    deliveryNote: "Delivery Note",
    paymentReceipt: "Payment Receipt",
    expense: "Expense",
    inventory: "Paint Stock",
    creditNote: "Credit Note",
    taxLabel: "GSTIN",
  },
  modules: {
    dashboard: true,
    customers: true,
    suppliers: true,
    products: true,
    inventory: true,
    sales: true,
    purchases: true,
    documents: true,
    payments: true,
    expenses: true,
    reports: true,
    employees: true,
  },
  productFields: [
    { id: "brand", label: "Brand", type: "text", required: true, visible: true, placeholder: "e.g. Asian Paints, Berger", showInTable: true, showInForm: true },
    { id: "colour", label: "Colour Shade / Code", type: "text", required: true, visible: true, placeholder: "e.g. Royale Blue #0942", showInTable: true, showInForm: true },
    { id: "finish", label: "Finish", type: "select", required: true, visible: true, options: ["Matt", "Gloss", "Satin", "Emulsion"], showInTable: true, showInForm: true },
    { id: "size", label: "Pack Size", type: "select", required: true, visible: true, options: ["500ml", "1L", "4L", "10L", "20L"], showInTable: true, showInForm: true },
    { id: "unit", label: "Unit", type: "text", required: true, visible: true, placeholder: "Liters / Can", showInTable: true, showInForm: true },
    { id: "purchasePrice", label: "Purchase Price (₹)", type: "currency", required: true, visible: true, showInTable: false, showInForm: true },
    { id: "sellingPrice", label: "Selling Price (₹)", type: "currency", required: true, visible: true, showInTable: true, showInForm: true },
    { id: "gstRate", label: "GST Rate (%)", type: "number", required: true, visible: true, placeholder: "18", showInTable: true, showInForm: true },
  ],
  documentTypes: [
    { id: "sales_bill", label: "Sales Bill", shortLabel: "Bill", prefix: "CWP-BILL", enabled: true, template: "modern", numberingEnabled: true, requiresDelivery: true },
    { id: "quotation", label: "Quotation", shortLabel: "Quote", prefix: "CWP-QT", enabled: true, template: "classic", numberingEnabled: true },
    { id: "delivery_note", label: "Delivery Note", shortLabel: "Delivery", prefix: "CWP-DN", enabled: true, template: "minimal", numberingEnabled: true, requiresDelivery: true },
    { id: "purchase_bill", label: "Purchase Bill", shortLabel: "Purchase", prefix: "CWP-PUR", enabled: true, template: "classic", numberingEnabled: true },
  ],
  dashboardWidgets: [
    { id: "sales_overview", title: "Sales Overview", type: "chart", enabled: true, width: "full" },
    { id: "stock_summary", title: "Paint Stock Summary", type: "metric", enabled: true, width: "half" },
    { id: "recent_bills", title: "Recent Sales Bills", type: "list", enabled: true, width: "half" },
  ],
  paymentConfig: {
    acceptedMethods: ["cash", "upi", "card", "bank_transfer"],
    defaultMethod: "upi",
    allowCredit: true,
    maxCreditDays: 30,
  },
  taxConfig: {
    taxSystem: "gst",
    defaultGstRate: 18,
    gstinRequired: true,
    hsnSacRequired: true,
    taxLabel: "GSTIN",
  },
  numberingConfig: {
    invoicePrefix: "CWP-BILL",
    purchasePrefix: "CWP-PUR",
    quotationPrefix: "CWP-QT",
    sequenceStart: 1001,
    resetFrequency: "yearly",
  },
};
