import { BusinessConfig } from "@/types/config";

export const revolgaBiogenicsConfig: BusinessConfig = {
  id: "revolga-biogenics-001",
  businessType: "medical_company",
  businessName: "Revolga Biogenics",
  tagline: "Medical & Healthcare Management System",
  currency: "INR",
  language: "en",
  gstin: "32ABCDC1234D1Z8",
  phone: "+91 94471 99887",
  email: "contact@revolgabiogenics.com",
  address: "Biogenics Park, Medical Zone",
  city: "Kochi",
  state: "Kerala",
  pincode: "682016",
  branding: {
    brandColor: "#0284c7",
    accentColor: "#0ea5e9",
    tagline: "Advancing Healthcare Through Quality Medical Solutions",
    theme: "light",
  },
  enabled: true,
  productTypes: [
    { id: "medicine", label: "Pharmaceutical Medicine", requireBatchExpiry: true },
    { id: "medical_device", label: "Medical Device / Equipment", requireBatchExpiry: false },
    { id: "surgical_product", label: "Surgical Supply", requireBatchExpiry: true },
    { id: "healthcare_product", label: "Healthcare & Wellness", requireBatchExpiry: false },
    { id: "other", label: "Other Medical Product", requireBatchExpiry: false },
  ],
  terminology: {
    customer: "Customer",
    customerPlural: "Customers / Healthcare Partners",
    supplier: "Supplier",
    supplierPlural: "Suppliers",
    product: "Medical Product",
    productPlural: "Medical Products",
    brand: "Brand",
    brandPlural: "Brands & Manufacturers",
    category: "Category",
    categoryPlural: "Categories",
    stock: "Inventory Stock",
    inventory: "Inventory",
    lowStock: "Low Stock Items",
    invoice: "Tax Invoice",
    invoicePlural: "Tax Invoices",
    salesBill: "Tax Invoice",
    salesBillPlural: "Tax Invoices",
    purchase: "Purchase Bill",
    purchasePlural: "Purchase Bills",
    purchaseBill: "Purchase Bill",
    purchaseBillPlural: "Purchase Bills",
    quotation: "Quotation",
    quotationPlural: "Quotations",
    estimate: "Estimate",
    deliveryNote: "Delivery Note",
    deliveryNotePlural: "Delivery Notes",
    creditNote: "Credit Note",
    creditNotePlural: "Credit Notes",
    debitNote: "Debit Note",
    debitNotePlural: "Debit Notes",
    expense: "Expense",
  },
  modules: {
    dashboard: true,
    customers: true,
    suppliers: true,
    products: true,
    inventory: true,
    sales: true,
    purchases: true,
    documents: true,
    payments: true,
    expenses: true,
    reports: true,
    employees: false,
  },
  productFields: [
    { id: "name", label: "Product Name", type: "text", required: true, showInTable: true, showInForm: true },
    { id: "category", label: "Category", type: "select", required: true, showInTable: true, showInForm: true },
    { id: "productType", label: "Product Type", type: "select", required: true, showInTable: true, showInForm: true },
    { id: "brand", label: "Brand / Manufacturer", type: "text", required: true, showInTable: true, showInForm: true },
    { id: "sellingPrice", label: "Selling Price (₹)", type: "currency", required: true, showInTable: true, showInForm: true },
    { id: "currentStock", label: "Current Stock", type: "number", required: true, showInTable: true, showInForm: true },
  ],
  documentTypes: [
    { id: "sales_invoice", name: "Tax Invoice", prefix: "INV", enabled: true, template: "modern" },
    { id: "purchase_bill", name: "Purchase Bill", prefix: "PUR", enabled: true, template: "modern" },
    { id: "quotation", name: "Quotation", prefix: "QTN", enabled: true, template: "modern" },
    { id: "delivery_note", name: "Delivery Note", prefix: "DC", enabled: true, template: "modern" },
    { id: "receipt", name: "Payment Receipt", prefix: "REC", enabled: true, template: "modern" },
    { id: "credit_note", name: "Credit Note", prefix: "CN", enabled: true, template: "modern" },
    { id: "debit_note", name: "Debit Note", prefix: "DN", enabled: true, template: "modern" },
    { id: "sales_return", name: "Sales Return", prefix: "SR", enabled: true, template: "modern" },
    { id: "purchase_return", name: "Purchase Return", prefix: "PR", enabled: true, template: "modern" },
  ],
  dashboardWidgets: [
    { id: "todaysSales", title: "Today's Sales", type: "metric", enabled: true, width: "third" },
    { id: "monthlySales", title: "Monthly Sales", type: "metric", enabled: true, width: "third" },
    { id: "totalOrders", title: "Total Orders", type: "metric", enabled: true, width: "third" },
    { id: "receivables", title: "Outstanding Receivables", type: "metric", enabled: true, width: "third" },
    { id: "payables", title: "Outstanding Payables", type: "metric", enabled: true, width: "third" },
    { id: "inventoryValue", title: "Inventory Value", type: "metric", enabled: true, width: "third" },
  ],
  paymentConfig: {
    acceptedMethods: ["cash", "upi", "card", "bank_transfer", "cheque"],
    defaultMethod: "bank_transfer",
    allowCredit: true,
    maxCreditDays: 30,
  },
  taxConfig: {
    taxSystem: "gst",
    defaultGstRate: 12,
    gstinRequired: true,
    hsnSacRequired: true,
    taxLabel: "GST",
  },
  numberingConfig: {
    invoicePrefix: "INV-",
    purchasePrefix: "PUR-",
    quotationPrefix: "QTN-",
    sequenceStart: 1,
    resetFrequency: "yearly",
  },
};
