import { BusinessConfig } from "@/types/config";

export const serviceBusinessConfig: BusinessConfig = {
  enabled: false, // Hidden: Phase 3 focuses on medical_distributor only
  id: "abc-digital-services",
  businessType: "service_business",
  businessName: "ABC Digital Services",
  tagline: "IT Solutions, Web & Mobile Consulting",
  currency: "INR",
  language: "en",
  gstin: "32SERVI1122S1Z4",
  phone: "+91 97450 33221",
  email: "hello@abcdigital.io",
  address: "Technopark Phase III, Karyavattom",
  city: "Thiruvananthapuram",
  state: "Kerala",
  pincode: "695581",
  branding: {
    brandColor: "#7c3aed",
    accentColor: "#8b5cf6",
    tagline: "Software & Digital Consulting",
    theme: "light",
  },
  terminology: {
    customer: "Client",
    customerPlural: "Clients",
    supplier: "Vendor",
    supplierPlural: "Vendors",
    product: "Service",
    productPlural: "Services",
    invoice: "Service Invoice",
    invoicePlural: "Service Invoices",
    purchase: "Contractor Bill",
    purchasePlural: "Contractor Bills",
    quotation: "Proposal / Estimate",
    estimate: "Estimate",
    deliveryNote: "Scope Document",
    paymentReceipt: "Payment Receipt",
    expense: "Expense",
    inventory: "Service Catalog",
    creditNote: "Credit Adjustment",
    taxLabel: "GSTIN / SAC",
  },
  modules: {
    dashboard: true,
    customers: true,
    suppliers: true,
    products: true,
    inventory: false, // CRITICAL: Physical Inventory module disabled for service business!
    sales: true,
    purchases: true,
    documents: true,
    payments: true,
    expenses: true,
    reports: true,
    employees: true,
  },
  productFields: [
    { id: "serviceName", label: "Service Name", type: "text", required: true, visible: true, placeholder: "e.g. Next.js Frontend Dev", showInTable: true, showInForm: true },
    { id: "serviceCategory", label: "Service Category", type: "select", required: true, visible: true, options: ["Software Development", "Mobile App Dev", "UI/UX Design", "Cloud Infrastructure", "SEO & Marketing"], showInTable: true, showInForm: true },
    { id: "billingType", label: "Billing Model", type: "select", required: true, visible: true, options: ["Hourly Rate", "Fixed Price", "Monthly Retainer", "Milestone Based"], showInTable: true, showInForm: true },
    { id: "deliverableScope", label: "Deliverable Scope", type: "textarea", required: false, visible: true, placeholder: "e.g. Architecture setup & API integration", showInTable: true, showInForm: true },
    { id: "sacCode", label: "SAC Code", type: "text", required: true, visible: true, placeholder: "e.g. 998314", showInTable: true, showInForm: true },
    { id: "sellingPrice", label: "Rate / Fee (₹)", type: "currency", required: true, visible: true, placeholder: "45000", showInTable: true, showInForm: true },
    { id: "gstRate", label: "GST Rate (%)", type: "number", required: true, visible: true, placeholder: "18", showInTable: true, showInForm: true },
  ],
  documentTypes: [
    { id: "service_invoice", label: "Service Invoice", shortLabel: "Invoice", prefix: "ADS-INV", enabled: true, template: "modern", numberingEnabled: true },
    { id: "estimate", label: "Proposal / Estimate", shortLabel: "Estimate", prefix: "ADS-EST", enabled: true, template: "professional", numberingEnabled: true },
    { id: "payment_receipt", label: "Payment Receipt", shortLabel: "Receipt", prefix: "ADS-REC", enabled: true, template: "minimal", numberingEnabled: true },
  ],
  dashboardWidgets: [
    { id: "revenue_runrate", title: "Monthly Retainer Revenue", type: "metric", enabled: true, width: "half" },
    { id: "unbilled_time", title: "Unbilled Project Hours", type: "metric", enabled: true, width: "half" },
    { id: "client_invoices", title: "Client Invoice Status", type: "list", enabled: true, width: "full" },
  ],
  paymentConfig: {
    acceptedMethods: ["bank_transfer", "upi", "cheque"],
    defaultMethod: "bank_transfer",
    allowCredit: true,
    maxCreditDays: 15,
  },
  taxConfig: {
    taxSystem: "gst",
    defaultGstRate: 18,
    gstinRequired: true,
    hsnSacRequired: true,
    taxLabel: "GSTIN / SAC",
  },
  numberingConfig: {
    invoicePrefix: "ADS-INV",
    purchasePrefix: "ADS-CB",
    quotationPrefix: "ADS-EST",
    sequenceStart: 1001,
    resetFrequency: "yearly",
  },
};
